---
- name: Hello World
  hosts: all
  vars_files: 
    -  ./vars/hello.yml
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible {{ var1 }}
    - include_tasks: tasks/hello.yml

- name: Hello World2
  hosts: all
  vars:
    var1: "eboo"
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible {{ var1 }}
   
- import_playbook: playbooks/playbook1.yml
- import_playbook: playbooks/rke2-install.yml