---
- name: Hello World
  hosts: all
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
    - include_tasks: tasks/hello.yml

- import_playbook: playbooks/playbook1.yml
- import_playbook: playbooks/rke2-install.yml
